# Letter codes standard for IUPAC. See here: https://www.bioinformatics.org/sms2/iupac.html
PFAM_VOCAB = {
    '<PAD>': 0,
    '<MASK>': 1,
    '<CLS>': 2,
    '<SEP>': 3,
    'A': 4,
    'B': 5,
    'C': 6,
    'D': 7,
    'E': 8,
    'F': 9,
    'G': 10,
    'H': 11,
    'I': 12,
    'K': 13,
    'L': 14,
    'M': 15,
    'N': 16,
    'O': 17,
    'P': 18,
    'Q': 19,
    'R': 20,
    'S': 21,
    'T': 22,
    'U': 23,
    'V': 24,
    'W': 25,
    'X': 26,
    'Y': 27,
    'Z': 28
}
